apiVersion: v1
kind: Service
metadata:
  name: test-service
  namespace: etop-dev
  labels:
    name: test-service
spec:
  type: LoadBalancer 
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080 
  #type: ClusterIP
  #ports:
  #- port: 8080
    #protocol: TCP
    #targetPort: 8080
    #nodeport: 30002
  selector:
    name: test-service-pod
 

  
