apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-service-deploy
  namespace: etop-prod
  labels:
    name: test-service-deploy
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      name: test-service-pod
  template:
    metadata:
      labels:
        name: test-service-pod
    spec:
      #initContainers:
      #- name: wait-for-db-postgres
        #image: busybox
        #command: ['sh', '-c', "until nslookup postgresql-pod; do echo waiting for postgresql-pod; sleep 2; done"]
      containers:  
      - name: test-service
        image: kypnt/etop-edutest-test-service
        imagePullPolicy: Always
        ports:
        - containerPort: 8080 #9001
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
        env:
        - name: SPRING_DATASOURCE_PASSWORD
          value: Ug5YCpXFKNe3gy
#           valueFrom:
             #secretKeyRef:
#              name: postgresql-secret
#              key: SPRING_DATASOURCE_PASSWORD
          #env:
          #- name: spring.profiles.active
            #ValueFrom:
              #configMapKeyRef:
                #name: postgresql-configmap
                #key: spring.profiles.active
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://pgsql-kypnt-prod.postgres.database.azure.com:5432/etop-prod?currentSchema=test-centre-service&sslmode=require
            #ValueFrom:
              #configMapKeyRef:
                #name: SPRING_DATASOURCE_URL
        env:
        - name: SPRING_DATASOURCE_USERNAME
          value: postgress
              #ValueFrom:
                #configMapKeyRef:
                  #name: postgresql-configmap
                  #key: SPRING_DATASOURCE_USERNAME
      imagePullSecrets:
      - name: regcred
      #tolerations:
      #- key: "talrise"
        #operator: "Equal"
        #value: "worker-2"
        #effect: "NoSchedule"
      #nodeSelector:
        #node: be-fe
      #nodeSelector:
      # agentpool: "agentpool"
