version: '3.9'
services:
  db-postgres:
    container_name: db-postgres
    image: postgres:13.7-alpine
    environment:
      POSTGRES_ROOT_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"] #-d postgres
      interval: 3s
      retries: 10
      start_period: 5s
      timeout: 5s   
    restart: always
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - "/root/postgresql-data:/var/lib/postgresql/data"
    networks:
      - talrise

  rec-service:
    container_name: rec-service
    image: ${DOCKERHUB_USER}/rec-service-uat:latest
    pull_policy: always
    restart: always
    environment:
      spring.profiles.active: test
      SERVER_PORT: ${REC_SERVICE_PORT}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASS}
      IAM_SERVICE_URL: ${IAM_SERVICE_URL}
    healthcheck:
      test: curl -s localhost:${REC_SERVICE_PORT}/api/health-check | jq --raw-output '.data.fileName' | grep 'bootstrap-sample.yml' 
      interval: 3s
      retries: 10
      start_period: 30s
      timeout: 5s
    ports:
      - ${REC_SERVICE_PORT}:${REC_SERVICE_PORT}
    volumes:
      #- "rec-service-vol:/var/lib/rec-service"
      - "/root/postgresql-data:/var/lib/rec-service"
    networks:
      - talrise
    depends_on:
      db-postgres:
        condition: service_healthy
      iam-service:
        condition: service_healthy

  iam-service:
    container_name: iam-service
    image: ${DOCKERHUB_USER}/iam-service-uat:latest
    pull_policy: always
    restart: always
    environment:
      spring.profiles.active: test
      SERVER_PORT: ${IAM_SERVICE_PORT}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASS}
    healthcheck:
      test: curl -s localhost:${IAM_SERVICE_PORT}/api/health-check | jq --raw-output '.data.fileName' | grep 'bootstrap-sample.yml'
      interval: 3s
      retries: 10
      start_period: 20s
      timeout: 5s
    ports:
      - ${IAM_SERVICE_PORT}:${IAM_SERVICE_PORT}
    volumes:
      #- "iam-service-vol:/var/lib/iam-service"
      - "/root/postgresql-data:/var/lib/iam-service"
    networks:
      - talrise
    depends_on:
      db-postgres:
        condition: service_healthy

volumes:
  rec-service-vol:
  iam-service-vol:

networks:
  talrise:
    driver: bridge
