apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: axis-examinion-cert
spec:
  secretName: tls-auto-axis-examinion
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod-axis-examinion
    commanName: "axis.examinion.com"
  dnsNames:
    - "axis.examinion.com"
