apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod-edutest-examinion
  namespace: default
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: devops@kypnt.co.uk
    privateKeySecretRef:
      name: tls-auto-edutest-examinion
    solvers:
    - http01:
        ingress:
          class: etop-prod-ingress
