apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql-deploy
  labels:
    app: postgresql-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql-pod
  template:
    metadata:
      labels:
        app: postgresql-pod
    spec:
      containers:
      - name: db-postgres
        image: postgres:13.7-alpine
        imagePullPolicy: Always
        ports:
        - containerPort: 5432 #${DB_PORT}
        livenessProbe:
          tcpSocket:
            port: 5432 #${DB_PORT}
          initialDelaySeconds: 15
          periodSeconds: 20
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresql-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresql-secret
              key: POSTGRES_ROOT_PASSWORD
        - name: POSTGRES_USER
          value: postgres
        - name: PGDATA                         bunu eklememizin nedeni yaml file create olurken fail oluyor ve container olusmuyordu. cunku mountpath ile belirledigimiz /var/lib/postgresql/data altinin dolu olmasi PGDATA sayesinde bu problem cozuldu. 
          value: /var/lib/postgresql/data/pg    
        #- name: DB_PORT
        #  value: 5432
        #envFrom:
        #- name: POSTGRES_USER
        #  valueFrom: 
        #  - configMapKeyRef:
        #      name: postgresql-configmap
        #      key: POSTGRES_USER
        #- name: DB_PORT
        #  valueFrom: 
        #  - configMapKeyRef:
        #      name: postgresql-configmap
        #      key: DB_PORT
        volumeMounts:
        - name: postgresql-persistentvolume
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgresql-persistentvolume
        persistentVolumeClaim:
          claimName: postgresql-pv-claim
          #claimName: talrise-pv-claim
      #tolerations:
      #- key: "talrise"
        #operator: "Equal"
        #value: "db-worker"
        #effect: "NoSchedule"
        ##effect: "NoSchedule"

