apiVersion: v1
kind: Service
metadata:
  name: postgresql-service
  labels:
    app: postgresql-deploy
spec:
  ports:
  - port: 5432 #${DB_PORT} this is the service port
    protocol: TCP
    targetPort: 5432 #${DB_PORT} this is the container port
  selector:
    app: postgresql-pod