version: '3.8'

volumes:
    sonarqube-data:

    nexus-data:
    
services:
    nexus3:
        ports:
            - '8081:8081'
        container_name: nexus
        volumes:
            - nexus-data:/nexus-data
        restart: always
        image: sonatype/nexus3
        networks:
            - kypnt

    sonarqube:
        container_name: sonarqube
        ports:
            - '9000:9000'
        volumes:
            - sonarqube-data:/opt/sonarqube/data
        restart: always
        image: 'sonarqube:9.4.0-community'
        networks:
            - kypnt

networks:
    kypnt:
        driver: bridge
