global:
  scrape_interval:     5s   # Set the scrape interval to every 5 seconds.
  evaluation_interval: 5s   # Evaluate rules every 5 seconds.
scrape_configs:
  - job_name: 'organization-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
    - targets: ['organization-service:8081']
  - job_name: 'user-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
    - targets: ['user-service:8082']