apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: etop-dev-fe-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend-service-deploy
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60
