apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: etop-prod
  labels:
    name: frontend-service
spec:
  #type: LoadBalancer   #NodePort
  #ports:
  #- port: 80
    #protocol: TCP
    #targetPort: 80 
  type: LoadBalancer   #NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    #nodeport: 30001
  selector:
    name: frontend-service-pod
