apiVersion: v1
kind: Service
metadata:
  name: notification-service
  labels:
    app: notification
spec:
  ports:
    - port: 9003
      targetPort: 9003
  selector:
    app: notification
